# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='pair',
            new_name='coin',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='lifetime',
            new_name='percent',
        ),
    ]
