# Generated by Django 2.0.4 on 2018-05-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=0, default=60, max_digits=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='price',
        ),
        migrations.AddField(
            model_name='buy',
            name='amountBTC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='amountETH',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='amountWAVES',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='name',
            field=models.CharField(default='Buy', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='percentBTC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='percentETH',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='percentWAVES',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='priceBTC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='priceETH',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='priceWAVES',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='amountBTC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='amountETH',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='amountWAVES',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='name',
            field=models.CharField(default='Sell', max_length=5),
        ),
        migrations.AddField(
            model_name='sell',
            name='percentBTC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='percentETH',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='percentWAVES',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='priceBTC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='priceETH',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='priceWAVES',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
