# Generated by Django 2.0.4 on 2018-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180507_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='name',
        ),
        migrations.AlterField(
            model_name='buy',
            name='percentBTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='buy',
            name='percentETH',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='buy',
            name='percentWAVES',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sell',
            name='percentBTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sell',
            name='percentETH',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sell',
            name='percentWAVES',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
