# Generated by Django 2.0.4 on 2018-05-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180507_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
