# Generated by Django 2.0.4 on 2018-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20180508_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timecheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecheck', models.DecimalField(decimal_places=0, default=60, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Timeprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeprice', models.DecimalField(decimal_places=0, default=60, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='buy',
            name='amountBTCtoken',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='amountETHtoken',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='buy',
            name='amountWAVEStoken',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='SamountBTCtoken',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='SamountETHtoken',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sell',
            name='SamountWAVEStoken',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
    ]
