# Generated by Django 2.0.4 on 2018-05-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20180508_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebuyback', models.DecimalField(decimal_places=0, default=60, max_digits=6)),
                ('statusBTC', models.BooleanField(default=False)),
                ('statusETH', models.BooleanField(default=False)),
                ('statusWAVES', models.BooleanField(default=False)),
                ('amountBTC', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('amountETH', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('amountWAVES', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
            ],
        ),
    ]
