# Generated by Django 2.0.4 on 2018-05-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_threshhold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyback',
            name='statusBTC',
        ),
        migrations.RemoveField(
            model_name='buyback',
            name='statusETH',
        ),
        migrations.RemoveField(
            model_name='buyback',
            name='statusWAVES',
        ),
    ]
