# Generated by Django 2.0.4 on 2018-05-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20180509_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyback',
            old_name='amountBTC',
            new_name='bbamountBTC',
        ),
        migrations.RenameField(
            model_name='buyback',
            old_name='amountETH',
            new_name='bbamountETH',
        ),
        migrations.RenameField(
            model_name='buyback',
            old_name='amountWAVES',
            new_name='bbamountWAVES',
        ),
        migrations.AddField(
            model_name='buyback',
            name='statusbb',
            field=models.BooleanField(default=False),
        ),
    ]
